stages:
  - build-dev
  - deploy-dev

build-dev:
  stage: build-dev
  # only:
  #   - dev
  tags:
    - debian
    - dss
  script:
    - docker build -t webx-router-builder .
    - docker create -ti --name webx-router-builder webx-router-builder bash
    - docker cp webx-router-builder:/app/target/debian/. .
    - docker rm -f webx-router-builder
    - PACKAGE_VERSION=`awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' Cargo.toml`
    - cp webx-router_${PACKAGE_VERSION}_amd64.deb webx-router_dev_amd64.deb
  artifacts:
    paths:
      - webx-router_dev_amd64.deb
    expire_in: 1 week

deploy-dev:
  stage: deploy-dev
  # only:
  #   - dev
  tags:
    - debian
    - dss
  script:
    - scp webx-router_dev_amd64.deb webx@webx-dev.ill.fr:/data/deb/
    - ssh webx@webx-dev.ill.fr "cd /data/apps/webx-deploy; git pull --rebase origin dev;"
    - ssh root@webx-dev.ill.fr "cd /data/apps/webx-deploy; ./deploy-deb.sh"
