[package]
name = "webx-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9.2"
env_logger = "0.9.0"
log = "0.4.14"
ctrlc = "3.2.1"
config = "0.11.0"
serde = {version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
