logging: info
transport:
  ports:
    connector: 5555
    publisher: 5556
    collector: 5557
    session: 5558
  ipc:
    message_proxy: "ipc:///tmp/webx-router-message-proxy.ipc"
    instruction_proxy: "ipc:///tmp/webx-router-instruction-proxy.ipc"
  encryption:
    public: ""
    private: ""
