logging: info
transport:
  ports:
    connector: 5555
    publisher: 5556
    collector: 5557
    session: 5558
  ipc:
    message_proxy: "/tmp/webx-router-message-proxy.ipc"
    instruction_proxy: "/tmp/webx-router-instruction-proxy.ipc"
    engine_connector_root: "/tmp/webx-engine-session-connector"
    sesman_connector: "/tmp/webx-session-manager.ipc"
  encryption:
    public: ""
    private: ""
sesman:
  enabled: true
  fallback_display_id: ":0"
  auto_logout_s: 600
engine:
  path: /usr/bin/webx-engine
  logdir: /var/log/webx/engine