#!/bin/sh

set -e

#DEBHELPER#

systemctl_stop() {
    unit="$1"

    echo "Stopping $unit"
    systemctl stop -q "$unit" || true

    for i in $(seq 20); do
        echo "Waiting until $unit is stopped [attempt $i]"
        if ! systemctl is-active -q "$unit"; then
            echo "$unit is stopped."
            return
        fi
        sleep .1
    done
}

if [ "$1" = "remove" ]; then
    systemctl_stop "webx-router"
fi
